[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
onchain_ticket_solution = "92z53zQ9AuDC1s7xjgmiLfaPRpdkvPKsgFQK95V6MY7k"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/hoooooou_jun/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
